-- Insert countries into the country table
INSERT INTO country (country_name) VALUES
('Afghanistan'),
('Albania'),
('Algeria'),
('Andorra'),
('Angola'),
('Antigua and Barbuda'),
('Argentina'),
('Armenia'),
('Australia'),
('Austria'),
('Bahamas'),
('Bahrain'),
('Bangladesh'),
('Barbados'),
('Belarus'),
('Belgium'),
('Belize'),
('Benin'),
('Bhutan'),
('Bolivia'),
('Bosnia and Herzegovina'),
('Botswana'),
('Brazil'),
('Brunei'),
('Bulgaria'),
('Burkina Faso'),
('Burundi'),
('Cabo Verde'),
('Cambodia'),
('Cameroon'),
('Canada'),
('Central African Republic'),
('Chad'),
('Chile'),
('China'),
('Colombia'),
('Comoros'),
('Congo (Congo-Brazzaville)'),
('Costa Rica'),
('Côte d''Ivoire'),
('Croatia'),
('Cuba'),
('Cyprus'),
('Czechia (Czech Republic)'),
('Democratic Republic of the Congo'),
('Denmark'),
('Djibouti'),
('Dominica'),
('Dominican Republic'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('Equatorial Guinea'),
('Eritrea'),
('Eswatini (fmr. ''Swaziland'')'),
('Estonia'),
('Ethiopia'),
('Fiji'),
('Finland'),
('France'),
('Gabon'),
('Gambia'),
('Georgia'),
('Germany'),
('Ghana'),
('Greece'),
('Grenada'),
('Guatemala'),
('Guinea'),
('Guinea-Bissau'),
('Guyana'),
('Haiti'),
('Holy See'),
('Honduras'),
('Hong Kong'),
('Hungary'),
('Iceland'),
('India'),
('Indonesia'),
('Iran'),
('Iraq'),
('Ireland'),
('Israel'),
('Italy'),
('Jamaica'),
('Japan'),
('Jordan'),
('Kazakhstan'),
('Kenya'),
('Kiribati'),
('Kuwait'),
('Kyrgyzstan'),
('Laos'),
('Latvia'),
('Lebanon'),
('Lesotho'),
('Liberia'),
('Libya'),
('Liechtenstein'),
('Lithuania'),
('London'),
('Luxembourg'),
('Madagascar'),
('Malawi'),
('Malaysia'),
('Maldives'),
('Mali'),
('Malta'),
('Marshall Islands'),
('Mauritania'),
('Mauritius'),
('Mexico'),
('Micronesia'),
('Moldova'),
('Monaco'),
('Mongolia'),
('Montenegro'),
('Morocco'),
('Mozambique'),
('Myanmar (formerly Burma)'),
('Namibia'),
('Nauru'),
('Nepal'),
('Netherlands'),
('New York, NY'),
('New Zealand'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('North Korea'),
('North Macedonia'),
('Norway'),
('Oman'),
('Pakistan'),
('Palau'),
('Palestine State'),
('Panama'),
('Papua New Guinea'),
('Paraguay'),
('Peru'),
('Philippines'),
('Poland'),
('Portugal'),
('Qatar'),
('Remote'),
('Romania'),
('Russia'),
('Rwanda'),
('Saint Kitts and Nevis'),
('Saint Lucia'),
('Saint Vincent and the Grenadines'),
('Samoa'),
('San Francisco, CA'),
('San Marino'),
('Sao Tome and Principe'),
('Saudi Arabia'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leone'),
('Singapore'),
('Slovakia'),
('Slovenia'),
('Solomon Islands'),
('Somalia'),
('South Africa'),
('South Korea'),
('South Sudan'),
('Spain'),
('Sri Lanka'),
('Sudan'),
('Suriname'),
('Sweden'),
('Switzerland'),
('Syria'),
('Taiwan'),
('Tajikistan'),
('Tanzania'),
('Thailand'),
('Timor-Leste'),
('Togo'),
('Tonga'),
('Trinidad and Tobago'),
('Tunisia'),
('Turkey'),
('Turkmenistan'),
('Tuvalu'),
('Uganda'),
('Ukraine'),
('United Arab Emirates'),
('United Kingdom'),
('United States'),
('Uruguay'),
('Uzbekistan'),
('Vanuatu'),
('Venezuela'),
('Vietnam'),
('Yemen'),
('Zambia'),
('Zimbabwe')
ON CONFLICT (country_name) DO NOTHING;


-- Insert experience levels into the experience_level table
INSERT INTO experience_level (experience_level) VALUES
('Internship'),
('New Grad'),
('Junior'),
('Mid Level'),
('Senior')
ON CONFLICT (experience_level) DO NOTHING;


-- Insert interview tags into the interview_tag table
INSERT INTO interview_tag (tag_name) VALUES
('Online Assessment'),
('HR/Recruiter'),
('Technical'),
('Behavioral'),
('Hiring Manager'),
('Final Round')
ON CONFLICT (tag_name) DO NOTHING;


-- Insert leetcode questions into the leetcode_question table
INSERT INTO leetcode_question (question_number, difficulty, leetcode_title, leetcode_url) VALUES
('1', 'Easy', 'Two Sum', 'two-sum'),
('2', 'Medium', 'Add Two Numbers', 'add-two-numbers'),
('3', 'Medium', 'Longest Substring Without Repeating Characters', 'longest-substring-without-repeating-characters'),
('4', 'Hard', 'Median of Two Sorted Arrays', 'median-of-two-sorted-arrays'),
('5', 'Medium', 'Longest Palindromic Substring', 'longest-palindromic-substring'),
('6', 'Medium', 'Zigzag Conversion', 'zigzag-conversion'),
('7', 'Medium', 'Reverse Integer', 'reverse-integer'),
('8', 'Medium', 'String to Integer (atoi)', 'string-to-integer-atoi'),
('9', 'Easy', 'Palindrome Number', 'palindrome-number'),
('10', 'Hard', 'Regular Expression Matching', 'regular-expression-matching'),
('11', 'Medium', 'Container With Most Water', 'container-with-most-water'),
('12', 'Medium', 'Integer to Roman', 'integer-to-roman'),
('13', 'Easy', 'Roman to Integer', 'roman-to-integer'),
('14', 'Easy', 'Longest Common Prefix', 'longest-common-prefix'),
('15', 'Medium', '3Sum', '3sum'),
('16', 'Medium', '3Sum Closest', '3sum-closest'),
('17', 'Medium', 'Letter Combinations of a Phone Number', 'letter-combinations-of-a-phone-number'),
('18', 'Medium', '4Sum', '4sum'),
('19', 'Medium', 'Remove Nth Node From End of List', 'remove-nth-node-from-end-of-list'),
('20', 'Easy', 'Valid Parentheses', 'valid-parentheses'),
('21', 'Easy', 'Merge Two Sorted Lists', 'merge-two-sorted-lists'),
('22', 'Medium', 'Generate Parentheses', 'generate-parentheses'),
('23', 'Hard', 'Merge k Sorted Lists', 'merge-k-sorted-lists'),
('24', 'Medium', 'Swap Nodes in Pairs', 'swap-nodes-in-pairs'),
('25', 'Hard', 'Reverse Nodes in k-Group', 'reverse-nodes-in-k-group'),
('26', 'Easy', 'Remove Duplicates from Sorted Array', 'remove-duplicates-from-sorted-array'),
('27', 'Easy', 'Remove Element', 'remove-element'),
('28', 'Easy', 'Find the Index of the First Occurrence in a String', 'find-the-index-of-the-first-occurrence-in-a-string'),
('29', 'Medium', 'Divide Two Integers', 'divide-two-integers'),
('30', 'Hard', 'Substring with Concatenation of All Words', 'substring-with-concatenation-of-all-words')
ON CONFLICT (question_number) DO NOTHING;